apiVersion: v1
kind: Service
metadata:
  name: compreface-admin
  labels:
    app.kubernetes.io/name: compreface-admin
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: compreface-admin
  ports:
    - name: http
      port: 8080
      targetPort: http
