# core: ingress hanya dari api & admin. Egress: TIDAK ADA (air-gapped; model sudah di image).
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: compreface-core
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: compreface-core
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: compreface-api
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: compreface-admin
      ports:
        - protocol: TCP
          port: 3000
  egress: []
